// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[username].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Card.tsx";
import * as $$1 from "./islands/Icons.tsx";
import * as $$2 from "./islands/Integrity.tsx";
import * as $$3 from "./islands/Intro.tsx";
import * as $$4 from "./islands/Journey.tsx";
import * as $$5 from "./islands/Meter.tsx";
import * as $$6 from "./islands/Nav.tsx";
import * as $$7 from "./islands/Page.tsx";
import * as $$8 from "./islands/Server.tsx";
import * as $$9 from "./islands/Sync.tsx";

const manifest = {
  routes: {
    "./routes/[username].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Card.tsx": $$0,
    "./islands/Icons.tsx": $$1,
    "./islands/Integrity.tsx": $$2,
    "./islands/Intro.tsx": $$3,
    "./islands/Journey.tsx": $$4,
    "./islands/Meter.tsx": $$5,
    "./islands/Nav.tsx": $$6,
    "./islands/Page.tsx": $$7,
    "./islands/Server.tsx": $$8,
    "./islands/Sync.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
