// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[username].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/api/soon.ts";
import * as $4 from "./routes/fastmeal.tsx";
import * as $5 from "./routes/history.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/sickkfashion.tsx";
import * as $$0 from "./islands/Design.tsx";
import * as $$1 from "./islands/Fashion.tsx";
import * as $$2 from "./islands/FoodMenu.tsx";
import * as $$3 from "./islands/Integrity.tsx";
import * as $$4 from "./islands/Intro.tsx";
import * as $$5 from "./islands/Journey.tsx";
import * as $$6 from "./islands/Option.tsx";
import * as $$7 from "./islands/Page.tsx";
import * as $$8 from "./islands/Pokedata.tsx";
import * as $$9 from "./islands/Pricing.tsx";
import * as $$10 from "./islands/Server.tsx";
import * as $$11 from "./islands/Share.tsx";

const manifest = {
  routes: {
    "./routes/[username].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/api/soon.ts": $3,
    "./routes/fastmeal.tsx": $4,
    "./routes/history.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/sickkfashion.tsx": $7,
  },
  islands: {
    "./islands/Design.tsx": $$0,
    "./islands/Fashion.tsx": $$1,
    "./islands/FoodMenu.tsx": $$2,
    "./islands/Integrity.tsx": $$3,
    "./islands/Intro.tsx": $$4,
    "./islands/Journey.tsx": $$5,
    "./islands/Option.tsx": $$6,
    "./islands/Page.tsx": $$7,
    "./islands/Pokedata.tsx": $$8,
    "./islands/Pricing.tsx": $$9,
    "./islands/Server.tsx": $$10,
    "./islands/Share.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
