// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_username_ from "./routes/[username].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $fastmeal from "./routes/fastmeal.tsx";
import * as $history from "./routes/history.tsx";
import * as $index from "./routes/index.tsx";
import * as $plan from "./routes/plan.tsx";
import * as $portfolio from "./routes/portfolio.tsx";
import * as $sickkfashion from "./routes/sickkfashion.tsx";
import * as $world from "./routes/world.tsx";
import * as $Fashion from "./islands/Fashion.tsx";
import * as $FoodMenu from "./islands/FoodMenu.tsx";
import * as $Intro from "./islands/Intro.tsx";
import * as $Journey from "./islands/Journey.tsx";
import * as $Page from "./islands/Page.tsx";
import * as $PokemonsWorld from "./islands/PokemonsWorld.tsx";
import * as $Pricing from "./islands/Pricing.tsx";
import * as $Server from "./islands/Server.tsx";
import * as $Share from "./islands/Share.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[username].tsx": $_username_,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/fastmeal.tsx": $fastmeal,
    "./routes/history.tsx": $history,
    "./routes/index.tsx": $index,
    "./routes/plan.tsx": $plan,
    "./routes/portfolio.tsx": $portfolio,
    "./routes/sickkfashion.tsx": $sickkfashion,
    "./routes/world.tsx": $world,
  },
  islands: {
    "./islands/Fashion.tsx": $Fashion,
    "./islands/FoodMenu.tsx": $FoodMenu,
    "./islands/Intro.tsx": $Intro,
    "./islands/Journey.tsx": $Journey,
    "./islands/Page.tsx": $Page,
    "./islands/PokemonsWorld.tsx": $PokemonsWorld,
    "./islands/Pricing.tsx": $Pricing,
    "./islands/Server.tsx": $Server,
    "./islands/Share.tsx": $Share,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
